name: Deploy to Yandex Cloud

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Login to Yandex Container Registry
      run: |
        echo '${{ secrets.YC_SA_KEY }}' | docker login --username json_key --password-stdin cr.yandex
        
    - name: Build and push Docker image
      run: |
        cd fstr
        docker build -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/fstr-app:latest .
        docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/fstr-app:latest
        
    - name: Setup YC CLI
      run: |
        curl -s https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
        echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH
        
    - name: Deploy to Yandex Cloud
      run: |
        echo '${{ secrets.YC_SA_KEY }}' > key.json
        yc config set service-account-key key.json
        
        yc serverless container revision deploy \
          --container-name fstr-container \
          --image cr.yandex/${{ secrets.YC_REGISTRY_ID }}/fstr-app:latest \
          --cores 1 \
          --memory 1GB \
          --service-account-id ajemccqakovcebbghpu0 \
          --environment "SECRET_KEY=${{ secrets.SECRET_KEY }}" \
          --environment "FSTR_DB_NAME=${{ secrets.FSTR_DB_NAME }}" \
          --environment "FSTR_DB_LOGIN=${{ secrets.FSTR_DB_LOGIN }}" \
          --environment "FSTR_DB_PASS=${{ secrets.FSTR_DB_PASS }}" \
          --environment "FSTR_DB_HOST=${{ secrets.FSTR_DB_HOST }}" \
          --environment "FSTR_DB_PORT=${{ secrets.FSTR_DB_PORT }}" \
          --environment "DEBUG=False"
