name: Deploy to Yandex Cloud

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Login to Yandex Container Registry
      run: |
        echo '${{ secrets.YC_SA_KEY }}' | docker login --username json_key --password-stdin cr.yandex
        
    - name: Build and push Docker image
      run: |
        docker build -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/fstr-app:latest .
        docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/fstr-app:latest
        
    - name: Setup YC CLI
      run: |
        curl -s https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
        echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH
        
    - name: Deploy to Yandex Cloud
      run: |
        echo '${{ secrets.YC_SA_KEY }}' > key.json
        yc config set service-account-key key.json
        
        yc serverless container revision deploy \
          --container-name fstr-container \
          --image cr.yandex/${{ secrets.YC_REGISTRY_ID }}/fstr-app:latest \
          --cores 1 \
          --memory 1GB \
          --environment \
            SECRET_KEY='${{ secrets.SECRET_KEY }}',\
            FSTR_DB_NAME='${{ secrets.FSTR_DB_NAME }}',\
            FSTR_DB_LOGIN='${{ secrets.FSTR_DB_LOGIN }}',\
            FSTR_DB_PASS='${{ secrets.FSTR_DB_PASS }}',\
            FSTR_DB_HOST='${{ secrets.FSTR_DB_HOST }}',\
            FSTR_DB_PORT='${{ secrets.FSTR_DB_PORT }}',\
            DEBUG=False
